// src/components/Navbar.svelte
<script lang="ts">
</script>

<div class="navbar">
    <div class="left">
        <div class="logo">
          <img src="/avatar.png" />
        </div>
    </div>
    <div class="right">
      <div class="home"><a href="#/">Home</a></div>
      <div class="projects"><a href="#/projects">Projects</a></div>
      <div class="files"><a href="https://github.com/Percslol">GitHub</a></div>
    </div>
</div>

<style>
.navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 20px;
    color: white;
}

.navbar .left .logo img {
    margin-right: 10px;
    height: 40px;
}

.navbar .right {
    display: flex;
    gap: 20px;
}

.navbar .right a {
    text-decoration: none;
    color: white;
    font-size: 1rem;
    transition: color 0.3s ease;
}

.navbar .right a:hover {
    color: #12f39d;
}

@media (max-width: 768px) {
    .navbar {
        flex-direction: column;
        align-items: flex-start;
    }

    .navbar .right {
        width: 100%;
        justify-content: space-between;
        margin-top: 10px;
    }
}
</style>

// src/layout/Navbar.tsx
import { css } from "dreamland/core";
import { Link } from "dreamland/router";

function Navbar() {
	return (
		<header>
			<nav>
				<Link href="/">home</Link>
				<br />
				<Link href="/projects">projects</Link>
				<br />
				<Link href="/contact">contact</Link>
			</nav>
		</header>
	);
}

Navbar.style = css`
	nav {
		display: flex;
		flex-direction: row;
		justify-content: flex-start;
		padding-left: 1.5rem;
		align-items: flex-start;
		flex-shrink: 0;
		gap: 1em;

		font-size: 0.9rem;
	}
`;
export default Navbar;
